name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 15.x]

    steps:
      - uses: actions/checkout@v2
      - uses: c-hive/gha-yarn-cache@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
        env:
          CI: true

      - name: Install packages
        env:
          CI: true
        run: yarn install --frozen-lockfile

      - name: Run tests
        env:
          CI: true
        run: yarn test

      - name: Build frontend
        env:
          CI: false
        run: yarn build

      - name: Build SSR
        env:
          CI: false
        run: yarn build:ssr

      - name: Run SSR
        env:
          CI: true
        run: yarn start